# For more information on how to configure this file, please see:
# https://docs.getdbt.com/docs/profile

stocks:
  target: prod

  outputs: # test and prod are identical, but their target names has significance in different build stages
    test:
      type: snowflake
      account: xi99543.us-east-2.aws

      user:      dbt
      password:  dbtPassword123
      role:      transform
      database:  FT_DB
      warehouse: FT_WH
      schema:    FT_STAGING

      threads: 8
      client_session_keep_alive: False

    prod:
      type: snowflake
      account: xi99543.us-east-2.aws

      user:      dbt
      password:  dbtPassword123
      role:      transform
      database:  FT_DB
      warehouse: FT_WH
      schema:    FT_STAGING

      threads: 8
      client_session_keep_alive: False