   # Gal Vakeselman: This is a workflow to test deployment status 

name: Test deployment from master

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      
      - name: Install Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install DBT
        run: |
          python -m pip install --upgrade pip
          pip install dbt-snowflake
          pip install awscli
  
      - name: Deploy
        run: |
         dbt deps --profiles-dir ./ci_profiles
         dbt run --profiles-dir ./ci_profiles
         dbt test --profiles-dir ./ci_profiles
         
      - name: Docs
        run: |
         dbt docs generate --profiles-dir ./ci_profiles
         aws s3 cp /home/runner/work/mdm.demos.dbt/mdm.demos.dbt/target/ s3://mdm-dbt --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }} # aws s3api list-buckets




